# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef45a5612b85f5139a103bd89a5d0b6f7f4dd210854a2978ca648c8acd33dc1e19f800b3e7d9f9607aa20829b268f1dc41cce0c448773d1059c16dc54dd500cd

test:
  secret_key_base: b5fb85051e63926bebfa303b369d7a1e2d5c680e4970dbdd9a8a597f5c8c746af01aeb5d01313e8ec3666543331017ea3598fe27761570dc37376bdf4f6bf870

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
